const BASE_URL = "https://travelparadise.work/api/"
 
export const APP_USER = BASE_URL + "appuser"
export const CITY = BASE_URL + "city"
export const HOTEL = BASE_URL + "hotel"
export const TOUR = BASE_URL + "tour"
export const TOUR_COMPANY = BASE_URL + "tourcompany"
export const ROOM = BASE_URL + "room"
export const TOUR_BOOKING = BASE_URL + "tourbooking"
export const APP_USER_LOGIN = BASE_URL + "appuser/login"
export const SEARCH_ROOM = BASE_URL + "room/searchrooms"
export const AD_HOTEL = BASE_URL + "adhotel"
export const AD_TOUR = BASE_URL + "adtour"
export const SEARCH_TOUR = BASE_URL + "tour/bycity"
export const AVAILABLE_ROOM = BASE_URL + "room/availablerooms"